### ISSUE TITLE
Reference To Incorrect Variable Name in HttpClient

### ISSUE THREAD

**Issue by danielkperez** [synapsepay/synapse-pay-rest#15]
The latest merge with PR #14 broke with a typo `$reponse` which should be `$response`. 
The version of the SDK as is now is unusable until this issue is fixed. 

I propose changing `src/SynapsePayRest/HttpClient.php` line 63 to:

```
if (is_null($response) || $response == false || curl_error($ch)) {
```

**Comment by etelford** [comment]
As @danielkperez linked, I've open [this PR](https://github.com/SynapseFI/SynapseFI-PHP/pull/16) to address the typo.
