### ISSUE TITLE
Make package available of Packagist

### ISSUE THREAD

**Issue by beyerz** [synapsepay/synapse-pay-rest#4]
Please could you make this package available through Packagist so that I do not need to manage custom repositories in my composer file

**Comment by Ben52** [comment]
Any update on this?

**Comment by sankaet** [comment]
Hi @Ben52 never got around doing this. But we are looking at this today and will update you soon.

**Comment by ngynmt** [comment]
@Ben52 The package is now available on Packagist. https://packagist.org/packages/synapsepay/synapse-pay-rest
